// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPkJlpustx7s1-u5pBEqDiXofWTGKQYdk',
    appId: '1:60114902423:web:562dd0fc86fd9b8f2578d2',
    messagingSenderId: '60114902423',
    projectId: 'bakeet-317d1',
    authDomain: 'bakeet-317d1.firebaseapp.com',
    storageBucket: 'bakeet-317d1.firebasestorage.app',
    measurementId: 'G-CJTCQX63H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6QOQFlaSaUeb9WTlXRiRGSk_Ix5a9ss',
    appId: '1:60114902423:android:1e8bf47d336eec472578d2',
    messagingSenderId: '60114902423',
    projectId: 'bakeet-317d1',
    storageBucket: 'bakeet-317d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKyD1sp0tg70ARwHY93J09hUfcNY-PWug',
    appId: '1:60114902423:ios:a01e98ffac15b2e52578d2',
    messagingSenderId: '60114902423',
    projectId: 'bakeet-317d1',
    storageBucket: 'bakeet-317d1.firebasestorage.app',
    iosBundleId: 'com.enjaz.noon_express',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKyD1sp0tg70ARwHY93J09hUfcNY-PWug',
    appId: '1:60114902423:ios:a01e98ffac15b2e52578d2',
    messagingSenderId: '60114902423',
    projectId: 'bakeet-317d1',
    storageBucket: 'bakeet-317d1.firebasestorage.app',
    iosBundleId: 'com.enjaz.noon_express',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPkJlpustx7s1-u5pBEqDiXofWTGKQYdk',
    appId: '1:60114902423:web:665f36439d5e30bf2578d2',
    messagingSenderId: '60114902423',
    projectId: 'bakeet-317d1',
    authDomain: 'bakeet-317d1.firebaseapp.com',
    storageBucket: 'bakeet-317d1.firebasestorage.app',
    measurementId: 'G-GFKETHQKJK',
  );
}
